// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package crawler

// Represents programming constructs like variables, classes, interfaces etc.
// that appear in a document. Document symbols can be hierarchical and they
// have two ranges: one that encloses its definition and one that points to
// its most interesting range, e.g. the range of an identifier.
type ClassSymbol struct {
	// Children of this symbol, e.g. properties of a class.
	Children []ClassSymbolChildrenElem `json:"children" yaml:"children" mapstructure:"children"`

	// Indicates if this symbol is deprecated.
	Deprecated bool `json:"deprecated" yaml:"deprecated" mapstructure:"deprecated"`

	// Documentation of this symbol.
	Documentation string `json:"documentation" yaml:"documentation" mapstructure:"documentation"`

	// The name of this symbol. Will be displayed in the user interface and therefore
	// must not be
	// an empty string or a string only consisting of white spaces.
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

type ClassSymbolChildrenElem interface{}

type Symbol interface{}
