// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package symbol

type Array struct {
	// Items corresponds to the JSON schema field "items".
	Items ArrayItems `json:"items" yaml:"items" mapstructure:"items"`

	// Kind corresponds to the JSON schema field "kind".
	Kind ArrayKind `json:"kind" yaml:"kind" mapstructure:"kind"`
}

type ArrayItems interface{}

type ArrayKind string

const ArrayKindArray ArrayKind = "array"

type BooleanLiteral struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind BooleanLiteralKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Value corresponds to the JSON schema field "value".
	Value BooleanLiteralValue `json:"value" yaml:"value" mapstructure:"value"`
}

type BooleanLiteralKind string

const BooleanLiteralKindBooleanliteral BooleanLiteralKind = "booleanliteral"

type BooleanLiteralValue string

const BooleanLiteralValueFalse BooleanLiteralValue = "false"
const BooleanLiteralValueTrue BooleanLiteralValue = "true"

// https://luals.github.io/wiki/annotations/#documenting-types
type Builtin struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind BuiltinKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Value corresponds to the JSON schema field "value".
	Value BuiltinValue `json:"value" yaml:"value" mapstructure:"value"`
}

type BuiltinKind string

const BuiltinKindBuiltin BuiltinKind = "builtin"

type BuiltinValue string

const BuiltinValueAny BuiltinValue = "any"
const BuiltinValueBoolean BuiltinValue = "boolean"
const BuiltinValueFunction BuiltinValue = "function"
const BuiltinValueInteger BuiltinValue = "integer"
const BuiltinValueLightuserdata BuiltinValue = "lightuserdata"
const BuiltinValueNil BuiltinValue = "nil"
const BuiltinValueNumber BuiltinValue = "number"
const BuiltinValueString BuiltinValue = "string"
const BuiltinValueTable BuiltinValue = "table"
const BuiltinValueThread BuiltinValue = "thread"
const BuiltinValueUserdata BuiltinValue = "userdata"
const BuiltinValueVoid BuiltinValue = "void"

type Documentation []string

type Function struct {
	// Access corresponds to the JSON schema field "access".
	Access *string `json:"access,omitempty" yaml:"access,omitempty" mapstructure:"access,omitempty"`

	// Arguments corresponds to the JSON schema field "arguments".
	Arguments []FunctionArgument `json:"arguments" yaml:"arguments" mapstructure:"arguments"`

	// Deprecated corresponds to the JSON schema field "deprecated".
	Deprecated bool `json:"deprecated" yaml:"deprecated" mapstructure:"deprecated"`

	// Documentation corresponds to the JSON schema field "documentation".
	Documentation Documentation `json:"documentation" yaml:"documentation" mapstructure:"documentation"`

	// Generics corresponds to the JSON schema field "generics".
	Generics []FunctionGeneric `json:"generics" yaml:"generics" mapstructure:"generics"`

	// Kind corresponds to the JSON schema field "kind".
	Kind FunctionKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// Overloads corresponds to the JSON schema field "overloads".
	Overloads []FunctionOverload `json:"overloads,omitempty" yaml:"overloads,omitempty" mapstructure:"overloads,omitempty"`

	// Returns corresponds to the JSON schema field "returns".
	Returns []FunctionReturn `json:"returns" yaml:"returns" mapstructure:"returns"`
}

type FunctionArgument struct {
	// Documentation corresponds to the JSON schema field "documentation".
	Documentation Documentation `json:"documentation,omitempty" yaml:"documentation,omitempty" mapstructure:"documentation,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Optional corresponds to the JSON schema field "optional".
	Optional bool `json:"optional" yaml:"optional" mapstructure:"optional"`

	// Type corresponds to the JSON schema field "type".
	Type FunctionArgumentType `json:"type" yaml:"type" mapstructure:"type"`
}

type FunctionArgumentType interface{}

type FunctionGeneric struct {
	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Types corresponds to the JSON schema field "types".
	Types []FunctionGenericTypesElem `json:"types" yaml:"types" mapstructure:"types"`
}

type FunctionGenericTypesElem interface{}

type FunctionKind string

const FunctionKindFunction FunctionKind = "function"

type FunctionOverload struct {
	// Arguments corresponds to the JSON schema field "arguments".
	Arguments []FunctionArgument `json:"arguments" yaml:"arguments" mapstructure:"arguments"`

	// Documentation corresponds to the JSON schema field "documentation".
	Documentation Documentation `json:"documentation" yaml:"documentation" mapstructure:"documentation"`

	// Generics corresponds to the JSON schema field "generics".
	Generics []FunctionGeneric `json:"generics" yaml:"generics" mapstructure:"generics"`

	// Returns corresponds to the JSON schema field "returns".
	Returns []FunctionReturn `json:"returns" yaml:"returns" mapstructure:"returns"`
}

type FunctionReturn struct {
	// Documentation corresponds to the JSON schema field "documentation".
	Documentation Documentation `json:"documentation,omitempty" yaml:"documentation,omitempty" mapstructure:"documentation,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type FunctionReturnType `json:"type" yaml:"type" mapstructure:"type"`
}

type FunctionReturnType interface{}

type NumericLiteral struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind NumericLiteralKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Value corresponds to the JSON schema field "value".
	Value string `json:"value" yaml:"value" mapstructure:"value"`
}

type NumericLiteralKind string

const NumericLiteralKindNumericliteral NumericLiteralKind = "numericliteral"

type Optional struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind OptionalKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Type corresponds to the JSON schema field "type".
	Type OptionalType `json:"type" yaml:"type" mapstructure:"type"`
}

type OptionalKind string

const OptionalKindOptional OptionalKind = "optional"

type OptionalType interface{}

type Reference struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind ReferenceKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Value corresponds to the JSON schema field "value".
	Value string `json:"value" yaml:"value" mapstructure:"value"`
}

type ReferenceKind string

const ReferenceKindReference ReferenceKind = "reference"

type StringLiteral struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind StringLiteralKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Value corresponds to the JSON schema field "value".
	Value string `json:"value" yaml:"value" mapstructure:"value"`
}

type StringLiteralKind string

const StringLiteralKindStringliteral StringLiteralKind = "stringliteral"

type Symbol interface{}

type Table struct {
	// Documentation corresponds to the JSON schema field "documentation".
	Documentation Documentation `json:"documentation" yaml:"documentation" mapstructure:"documentation"`

	// Fields corresponds to the JSON schema field "fields".
	Fields []TableField `json:"fields" yaml:"fields" mapstructure:"fields"`

	// Indexes corresponds to the JSON schema field "indexes".
	Indexes []TableIndex `json:"indexes,omitempty" yaml:"indexes,omitempty" mapstructure:"indexes,omitempty"`

	// Kind corresponds to the JSON schema field "kind".
	Kind TableKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

type TableField struct {
	// Deprecated corresponds to the JSON schema field "deprecated".
	Deprecated bool `json:"deprecated" yaml:"deprecated" mapstructure:"deprecated"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Optional corresponds to the JSON schema field "optional".
	Optional bool `json:"optional" yaml:"optional" mapstructure:"optional"`

	// Package corresponds to the JSON schema field "package".
	Package bool `json:"package" yaml:"package" mapstructure:"package"`

	// Private corresponds to the JSON schema field "private".
	Private bool `json:"private" yaml:"private" mapstructure:"private"`

	// Protected corresponds to the JSON schema field "protected".
	Protected bool `json:"protected" yaml:"protected" mapstructure:"protected"`

	// Value corresponds to the JSON schema field "value".
	Value TableFieldValue `json:"value" yaml:"value" mapstructure:"value"`
}

type TableFieldValue interface{}

type TableIndex struct {
	// Deprecated corresponds to the JSON schema field "deprecated".
	Deprecated bool `json:"deprecated" yaml:"deprecated" mapstructure:"deprecated"`

	// Key corresponds to the JSON schema field "key".
	Key TableIndexKey `json:"key" yaml:"key" mapstructure:"key"`

	// Optional corresponds to the JSON schema field "optional".
	Optional bool `json:"optional" yaml:"optional" mapstructure:"optional"`

	// Package corresponds to the JSON schema field "package".
	Package bool `json:"package" yaml:"package" mapstructure:"package"`

	// Private corresponds to the JSON schema field "private".
	Private bool `json:"private" yaml:"private" mapstructure:"private"`

	// Protected corresponds to the JSON schema field "protected".
	Protected bool `json:"protected" yaml:"protected" mapstructure:"protected"`

	// Value corresponds to the JSON schema field "value".
	Value TableIndexValue `json:"value" yaml:"value" mapstructure:"value"`
}

type TableIndexKey interface{}

type TableIndexValue interface{}

type TableKind string

const TableKindTable TableKind = "table"

type Union struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind UnionKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Types corresponds to the JSON schema field "types".
	Types []UnionTypesElem `json:"types" yaml:"types" mapstructure:"types"`
}

type UnionKind string

const UnionKindUnion UnionKind = "union"

type UnionTypesElem interface{}

type Unknown struct {
	// Documentation corresponds to the JSON schema field "documentation".
	Documentation Documentation `json:"documentation" yaml:"documentation" mapstructure:"documentation"`

	// Kind corresponds to the JSON schema field "kind".
	Kind UnknownKind `json:"kind" yaml:"kind" mapstructure:"kind"`
}

type UnknownKind string

const UnknownKindUnknown UnknownKind = "unknown"
