// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package lsp

import "encoding/json"
import "fmt"
import "reflect"

// A completion item represents a text snippet that is
// proposed to complete text that is being typed.
//
//	The CompletionItem namespace provides functions to deal with
//
// completion items.
type CompletionItem struct {
	// Indicates if this item is deprecated.
	Deprecated *bool `json:"deprecated,omitempty" yaml:"deprecated,omitempty" mapstructure:"deprecated,omitempty"`

	// A human-readable string with additional information
	// about this item, like type or symbol information.
	Detail *string `json:"detail,omitempty" yaml:"detail,omitempty" mapstructure:"detail,omitempty"`

	// A human-readable string that represents a doc-comment.
	Documentation *string `json:"documentation,omitempty" yaml:"documentation,omitempty" mapstructure:"documentation,omitempty"`

	// A string that should be inserted into a document when selecting
	// this completion. When `falsy` the [label](#CompletionItem.label)
	// is used.
	//
	// The `insertText` is subject to interpretation by the client side.
	// Some tools might not take the string literally. For example
	// VS Code when code complete is requested in this example `con<cursor position>`
	// and a completion item with an `insertText` of `console` is provided it
	// will only insert `sole`. Therefore it is recommended to use `textEdit` instead
	// since it avoids additional client side interpretation.
	InsertText *string `json:"insertText,omitempty" yaml:"insertText,omitempty" mapstructure:"insertText,omitempty"`

	// The format of the insert text. The format applies to both the `insertText`
	// property
	// and the `newText` property of a provided `textEdit`.
	InsertTextFormat *InsertTextFormat `json:"insertTextFormat,omitempty" yaml:"insertTextFormat,omitempty" mapstructure:"insertTextFormat,omitempty"`

	// The kind of this completion item. Based of the kind
	// an icon is chosen by the editor.
	Kind *CompletionItemKind `json:"kind,omitempty" yaml:"kind,omitempty" mapstructure:"kind,omitempty"`

	// The label of this completion item. By default
	// also the text that is inserted when selecting
	// this completion.
	Label string `json:"label" yaml:"label" mapstructure:"label"`
}

type CompletionItemKind float64

var enumValues_CompletionItemKind = []interface{}{
	1.0,
	2.0,
	3.0,
	4.0,
	5.0,
	6.0,
	7.0,
	8.0,
	9.0,
	10.0,
	11.0,
	12.0,
	13.0,
	14.0,
	15.0,
	16.0,
	17.0,
	18.0,
	19.0,
	20.0,
	21.0,
	22.0,
	23.0,
	24.0,
	25.0,
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CompletionItemKind) UnmarshalJSON(value []byte) error {
	var v float64
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_CompletionItemKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_CompletionItemKind, v)
	}
	*j = CompletionItemKind(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CompletionItem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["label"]; raw != nil && !ok {
		return fmt.Errorf("field label in CompletionItem: required")
	}
	type Plain CompletionItem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = CompletionItem(plain)
	return nil
}

// Represents a collection of [completion items](#CompletionItem) to be presented
// in the editor.
//
//	The CompletionList namespace provides functions to deal with
//
// completion lists.
type CompletionList struct {
	// This list it not complete. Further typing results in recomputing this list.
	IsIncomplete bool `json:"isIncomplete" yaml:"isIncomplete" mapstructure:"isIncomplete"`

	// The completion items.
	Items []CompletionItem `json:"items" yaml:"items" mapstructure:"items"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CompletionList) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["isIncomplete"]; raw != nil && !ok {
		return fmt.Errorf("field isIncomplete in CompletionList: required")
	}
	if _, ok := raw["items"]; raw != nil && !ok {
		return fmt.Errorf("field items in CompletionList: required")
	}
	type Plain CompletionList
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = CompletionList(plain)
	return nil
}

// Represents programming constructs like variables, classes, interfaces etc.
// that appear in a document. Document symbols can be hierarchical and they
// have two ranges: one that encloses its definition and one that points to
// its most interesting range, e.g. the range of an identifier.
type DocumentSymbol struct {
	// Children of this symbol, e.g. properties of a class.
	Children []DocumentSymbol `json:"children,omitempty" yaml:"children,omitempty" mapstructure:"children,omitempty"`

	// Indicates if this symbol is deprecated.
	Deprecated *bool `json:"deprecated,omitempty" yaml:"deprecated,omitempty" mapstructure:"deprecated,omitempty"`

	// More detail for this symbol, e.g the signature of a function.
	Detail *string `json:"detail,omitempty" yaml:"detail,omitempty" mapstructure:"detail,omitempty"`

	// The kind of this symbol.
	Kind SymbolKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// The name of this symbol. Will be displayed in the user interface and therefore
	// must not be
	// an empty string or a string only consisting of white spaces.
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// The range enclosing this symbol not including leading/trailing whitespace but
	// everything else
	// like comments. This information is typically used to determine if the the
	// clients cursor is
	// inside the symbol to reveal in the symbol in the UI.
	Range Range `json:"range" yaml:"range" mapstructure:"range"`

	// The range that should be selected and revealed when this symbol is being
	// picked, e.g the name of a function.
	// Must be contained by the the `range`.
	SelectionRange Range `json:"selectionRange" yaml:"selectionRange" mapstructure:"selectionRange"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DocumentSymbol) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in DocumentSymbol: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in DocumentSymbol: required")
	}
	if _, ok := raw["range"]; raw != nil && !ok {
		return fmt.Errorf("field range in DocumentSymbol: required")
	}
	if _, ok := raw["selectionRange"]; raw != nil && !ok {
		return fmt.Errorf("field selectionRange in DocumentSymbol: required")
	}
	type Plain DocumentSymbol
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = DocumentSymbol(plain)
	return nil
}

// A tagging type for string properties that are actually URIs.
type DocumentUri string

type InsertTextFormat float64

var enumValues_InsertTextFormat = []interface{}{
	1.0,
	2.0,
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *InsertTextFormat) UnmarshalJSON(value []byte) error {
	var v float64
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_InsertTextFormat {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_InsertTextFormat, v)
	}
	*j = InsertTextFormat(v)
	return nil
}

// Represents a location inside a resource, such as a line
// inside a text file.
//
//	The Location namespace provides helper functions to work with
//
// [Location](#Location) literals.
type Location struct {
	// Range corresponds to the JSON schema field "range".
	Range Range `json:"range" yaml:"range" mapstructure:"range"`

	// Uri corresponds to the JSON schema field "uri".
	Uri DocumentUri `json:"uri" yaml:"uri" mapstructure:"uri"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Location) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["range"]; raw != nil && !ok {
		return fmt.Errorf("field range in Location: required")
	}
	if _, ok := raw["uri"]; raw != nil && !ok {
		return fmt.Errorf("field uri in Location: required")
	}
	type Plain Location
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Location(plain)
	return nil
}

// A `MarkupContent` literal represents a string value which content is interpreted
// base on its
// kind flag. Currently the protocol supports `plaintext` and `markdown` as markup
// kinds.
//
// If the kind is `markdown` then the value can contain fenced code blocks like in
// GitHub issues.
// See
// https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting
//
// Here is an example how such a string can be constructed using JavaScript /
// TypeScript:
// ```ts
//
//	let markdown: MarkdownContent = {
//	  kind: MarkupKind.Markdown,
//
// value: [
//
//	'# Header',
//	'Some text',
//	'```typescript',
//	'someCode();',
//	'```'
//
// ].join('\n')
// };
// ```
//
// *Please Note* that clients might sanitize the return markdown. A client could
// decide to
// remove HTML from the markdown to avoid script execution.
type MarkupContent struct {
	// The type of the Markup
	Kind MarkupKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// The content itself
	Value string `json:"value" yaml:"value" mapstructure:"value"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MarkupContent) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in MarkupContent: required")
	}
	if _, ok := raw["value"]; raw != nil && !ok {
		return fmt.Errorf("field value in MarkupContent: required")
	}
	type Plain MarkupContent
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = MarkupContent(plain)
	return nil
}

type MarkupKind string

const MarkupKindMarkdown MarkupKind = "markdown"
const MarkupKindPlaintext MarkupKind = "plaintext"

var enumValues_MarkupKind = []interface{}{
	"plaintext",
	"markdown",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MarkupKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MarkupKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MarkupKind, v)
	}
	*j = MarkupKind(v)
	return nil
}

// Position in a text document expressed as zero-based line and character offset.
// The offsets are based on a UTF-16 string representation. So a string of the form
// `a𐐀b` the character offset of the character `a` is 0, the character offset of
// `𐐀`
// is 1 and the character offset of b is 3 since `𐐀` is represented using two code
// units in UTF-16.
//
// Positions are line end character agnostic. So you can not specify a position
// that
// denotes `\r|\n` or `\n|` where `|` represents the character offset.
//
//	The Position namespace provides helper functions to work with
//
// [Position](#Position) literals.
type Position struct {
	// Character offset on a line in a document (zero-based). Assuming that the line
	// is
	// represented as a string, the `character` value represents the gap between the
	// `character` and `character + 1`.
	//
	// If the character value is greater than the line length it defaults back to the
	// line length.
	// If a line number is negative, it defaults to 0.
	Character float64 `json:"character" yaml:"character" mapstructure:"character"`

	// Line position in a document (zero-based).
	// If a line number is greater than the number of lines in a document, it defaults
	// back to the number of lines in the document.
	// If a line number is negative, it defaults to 0.
	Line float64 `json:"line" yaml:"line" mapstructure:"line"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Position) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["character"]; raw != nil && !ok {
		return fmt.Errorf("field character in Position: required")
	}
	if _, ok := raw["line"]; raw != nil && !ok {
		return fmt.Errorf("field line in Position: required")
	}
	type Plain Position
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Position(plain)
	return nil
}

// A range in a text document expressed as (zero-based) start and end positions.
//
// If you want to specify a range that contains a line including the line ending
// character(s) then use an end position denoting the start of the next line.
// For example:
// ```ts
//
//	{
//	     start: { line: 5, character: 23 }
//	     end : { line 6, character : 0 }
//	}
//
// ```
//
//	The Range namespace provides helper functions to work with
//
// [Range](#Range) literals.
type Range struct {
	// The range's end position.
	End Position `json:"end" yaml:"end" mapstructure:"end"`

	// The range's start position
	Start Position `json:"start" yaml:"start" mapstructure:"start"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Range) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["end"]; raw != nil && !ok {
		return fmt.Errorf("field end in Range: required")
	}
	if _, ok := raw["start"]; raw != nil && !ok {
		return fmt.Errorf("field start in Range: required")
	}
	type Plain Range
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Range(plain)
	return nil
}

// Represents information about programming constructs like variables, classes,
// interfaces etc.
type SymbolInformation struct {
	// The name of the symbol containing this symbol. This information is for
	// user interface purposes (e.g. to render a qualifier in the user interface
	// if necessary). It can't be used to re-infer a hierarchy for the document
	// symbols.
	ContainerName *string `json:"containerName,omitempty" yaml:"containerName,omitempty" mapstructure:"containerName,omitempty"`

	// Indicates if this symbol is deprecated.
	Deprecated *bool `json:"deprecated,omitempty" yaml:"deprecated,omitempty" mapstructure:"deprecated,omitempty"`

	// The kind of this symbol.
	Kind SymbolKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// The location of this symbol. The location's range is used by a tool
	// to reveal the location in the editor. If the symbol is selected in the
	// tool the range's start information is used to position the cursor. So
	// the range usually spans more than the actual symbol's name and does
	// normally include thinks like visibility modifiers.
	//
	// The range doesn't have to denote a node range in the sense of a abstract
	// syntax tree. It can therefore not be used to re-construct a hierarchy of
	// the symbols.
	Location Location `json:"location" yaml:"location" mapstructure:"location"`

	// The name of this symbol.
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

type SymbolKind float64

var enumValues_SymbolKind = []interface{}{
	1.0,
	2.0,
	3.0,
	4.0,
	5.0,
	6.0,
	7.0,
	8.0,
	9.0,
	10.0,
	11.0,
	12.0,
	13.0,
	14.0,
	15.0,
	16.0,
	17.0,
	18.0,
	19.0,
	20.0,
	21.0,
	22.0,
	23.0,
	24.0,
	25.0,
	26.0,
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SymbolKind) UnmarshalJSON(value []byte) error {
	var v float64
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SymbolKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SymbolKind, v)
	}
	*j = SymbolKind(v)
	return nil
}

type CompletionItemDocumentation_1 = MarkupContent

// UnmarshalJSON implements json.Unmarshaler.
func (j *SymbolInformation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in SymbolInformation: required")
	}
	if _, ok := raw["location"]; raw != nil && !ok {
		return fmt.Errorf("field location in SymbolInformation: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in SymbolInformation: required")
	}
	type Plain SymbolInformation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SymbolInformation(plain)
	return nil
}

type TextDocumentCompletionResponse struct {
	// The result of a request. This member is REQUIRED on success.
	// This member MUST NOT exist if there was an error invoking the method.
	Result CompletionList `json:"result" yaml:"result" mapstructure:"result"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TextDocumentCompletionResponse) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["result"]; raw != nil && !ok {
		return fmt.Errorf("field result in TextDocumentCompletionResponse: required")
	}
	type Plain TextDocumentCompletionResponse
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = TextDocumentCompletionResponse(plain)
	return nil
}

type TextDocumentDocumentSymbolResponse struct {
	// The result of a request. This member is REQUIRED on success.
	// This member MUST NOT exist if there was an error invoking the method.
	Result []DocumentSymbol `json:"result" yaml:"result" mapstructure:"result"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TextDocumentDocumentSymbolResponse) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["result"]; raw != nil && !ok {
		return fmt.Errorf("field result in TextDocumentDocumentSymbolResponse: required")
	}
	type Plain TextDocumentDocumentSymbolResponse
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = TextDocumentDocumentSymbolResponse(plain)
	return nil
}
