// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package ts

import "encoding/json"
import "fmt"

type BufferLines []string

type TextDocumentTSAncestorBufferLinesResponse struct {
	// Result corresponds to the JSON schema field "result".
	Result BufferLines `json:"result" yaml:"result" mapstructure:"result"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TextDocumentTSAncestorBufferLinesResponse) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["result"]; raw != nil && !ok {
		return fmt.Errorf("field result in TextDocumentTSAncestorBufferLinesResponse: required")
	}
	type Plain TextDocumentTSAncestorBufferLinesResponse
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = TextDocumentTSAncestorBufferLinesResponse(plain)
	return nil
}
