// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package lexed

type Function struct {
	// Access corresponds to the JSON schema field "access".
	Access *string `json:"access,omitempty" yaml:"access,omitempty" mapstructure:"access,omitempty"`

	// Args corresponds to the JSON schema field "args".
	Args []FunctionArg `json:"args" yaml:"args" mapstructure:"args"`

	// Deprecated corresponds to the JSON schema field "deprecated".
	Deprecated bool `json:"deprecated" yaml:"deprecated" mapstructure:"deprecated"`

	// Doc corresponds to the JSON schema field "doc".
	Doc []string `json:"doc" yaml:"doc" mapstructure:"doc"`

	// Generics corresponds to the JSON schema field "generics".
	Generics []Generic `json:"generics" yaml:"generics" mapstructure:"generics"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Return corresponds to the JSON schema field "return".
	Return []FunctionReturn `json:"return" yaml:"return" mapstructure:"return"`

	// Visibility corresponds to the JSON schema field "visibility".
	Visibility *string `json:"visibility,omitempty" yaml:"visibility,omitempty" mapstructure:"visibility,omitempty"`
}

type FunctionArg struct {
	// Documentation corresponds to the JSON schema field "documentation".
	Documentation []string `json:"documentation,omitempty" yaml:"documentation,omitempty" mapstructure:"documentation,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Optional corresponds to the JSON schema field "optional".
	Optional bool `json:"optional" yaml:"optional" mapstructure:"optional"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

type FunctionReturn struct {
	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Optional corresponds to the JSON schema field "optional".
	Optional bool `json:"optional" yaml:"optional" mapstructure:"optional"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

type Generic struct {
	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Types corresponds to the JSON schema field "types".
	Types []string `json:"types" yaml:"types" mapstructure:"types"`
}

type Symbol interface{}
