// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package lexed

// https://luals.github.io/wiki/annotations/#documenting-types
type Builtin struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind BuiltinKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Value corresponds to the JSON schema field "value".
	Value BuiltinValue `json:"value" yaml:"value" mapstructure:"value"`
}

type BuiltinKind string

const BuiltinKindBuiltin BuiltinKind = "builtin"

type BuiltinValue string

const BuiltinValueAny BuiltinValue = "any"
const BuiltinValueBoolean BuiltinValue = "boolean"
const BuiltinValueFunction BuiltinValue = "function"
const BuiltinValueInteger BuiltinValue = "integer"
const BuiltinValueLightuserdata BuiltinValue = "lightuserdata"
const BuiltinValueNil BuiltinValue = "nil"
const BuiltinValueNumber BuiltinValue = "number"
const BuiltinValueString BuiltinValue = "string"
const BuiltinValueTable BuiltinValue = "table"
const BuiltinValueThread BuiltinValue = "thread"
const BuiltinValueUserdata BuiltinValue = "userdata"
const BuiltinValueVoid BuiltinValue = "void"

type Documentation []string

type Function struct {
	// Access corresponds to the JSON schema field "access".
	Access *string `json:"access,omitempty" yaml:"access,omitempty" mapstructure:"access,omitempty"`

	// Args corresponds to the JSON schema field "args".
	Args []FunctionArg `json:"args" yaml:"args" mapstructure:"args"`

	// Deprecated corresponds to the JSON schema field "deprecated".
	Deprecated bool `json:"deprecated" yaml:"deprecated" mapstructure:"deprecated"`

	// Documentation corresponds to the JSON schema field "documentation".
	Documentation Documentation `json:"documentation,omitempty" yaml:"documentation,omitempty" mapstructure:"documentation,omitempty"`

	// Generics corresponds to the JSON schema field "generics".
	Generics []FunctionGeneric `json:"generics" yaml:"generics" mapstructure:"generics"`

	// Kind corresponds to the JSON schema field "kind".
	Kind FunctionKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// Overloads corresponds to the JSON schema field "overloads".
	Overloads []FunctionOverload `json:"overloads,omitempty" yaml:"overloads,omitempty" mapstructure:"overloads,omitempty"`

	// Return corresponds to the JSON schema field "return".
	Return []FunctionReturn `json:"return" yaml:"return" mapstructure:"return"`
}

type FunctionArg struct {
	// Documentation corresponds to the JSON schema field "documentation".
	Documentation Documentation `json:"documentation,omitempty" yaml:"documentation,omitempty" mapstructure:"documentation,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Optional corresponds to the JSON schema field "optional".
	Optional bool `json:"optional" yaml:"optional" mapstructure:"optional"`

	// Type corresponds to the JSON schema field "type".
	Type FunctionArgType `json:"type" yaml:"type" mapstructure:"type"`
}

type FunctionArgType interface{}

type FunctionGeneric struct {
	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Types corresponds to the JSON schema field "types".
	Types []FunctionGenericTypesElem `json:"types" yaml:"types" mapstructure:"types"`
}

type FunctionGenericTypesElem interface{}

type FunctionKind string

const FunctionKindFunction FunctionKind = "function"

type FunctionOverload struct {
	// Args corresponds to the JSON schema field "args".
	Args []FunctionArg `json:"args" yaml:"args" mapstructure:"args"`

	// Documentation corresponds to the JSON schema field "documentation".
	Documentation Documentation `json:"documentation" yaml:"documentation" mapstructure:"documentation"`

	// Generics corresponds to the JSON schema field "generics".
	Generics []FunctionGeneric `json:"generics" yaml:"generics" mapstructure:"generics"`

	// Return corresponds to the JSON schema field "return".
	Return []FunctionReturn `json:"return" yaml:"return" mapstructure:"return"`
}

type FunctionReturn struct {
	// Documentation corresponds to the JSON schema field "documentation".
	Documentation Documentation `json:"documentation,omitempty" yaml:"documentation,omitempty" mapstructure:"documentation,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type FunctionReturnType `json:"type" yaml:"type" mapstructure:"type"`
}

type FunctionReturnType interface{}

type Reference struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind ReferenceKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Value corresponds to the JSON schema field "value".
	Value string `json:"value" yaml:"value" mapstructure:"value"`
}

type ReferenceKind string

const ReferenceKindReference ReferenceKind = "reference"

type Symbol interface{}

type Table struct {
	// Fields corresponds to the JSON schema field "fields".
	Fields []TableField `json:"fields" yaml:"fields" mapstructure:"fields"`

	// Kind corresponds to the JSON schema field "kind".
	Kind TableKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

type TableField struct {
	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Private corresponds to the JSON schema field "private".
	Private bool `json:"private" yaml:"private" mapstructure:"private"`

	// Protected corresponds to the JSON schema field "protected".
	Protected bool `json:"protected" yaml:"protected" mapstructure:"protected"`

	// Value corresponds to the JSON schema field "value".
	Value TableFieldValue `json:"value" yaml:"value" mapstructure:"value"`
}

type TableFieldValue interface{}

type TableKind string

const TableKindTable TableKind = "table"

type Unknown struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind UnknownKind `json:"kind" yaml:"kind" mapstructure:"kind"`
}

type UnknownKind string

const UnknownKindUnknown UnknownKind = "unknown"
